spring.application.name=auth-user-service
server.port=${PORT:8087}

spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://utsav:9228224337@cluster0.yslwcbv.mongodb.net/auth-user-db?retryWrites=true&w=majority}
spring.data.mongodb.auto-index-creation=false

jwt.secret=${JWT_SECRET:[REDACTED-JWT]}
jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:604800}

supabase.url=${SUPABASE_URL:https://wmjdpctpcfxulozvoqtx.supabase.co}
supabase.anon-key=${SUPABASE_ANON_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtamRwY3RwY2Z4dWxvenZvcXR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxNjU0NTEsImV4cCI6MjA5Mzc0MTQ1MX0.V86WUslacQgGBlxQ5tm-vDIlaTCuCG1fFL9YhZTZHws}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true