spring.application.name=wishlist-service
server.port=8084

spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://utsav:9228224337@cluster0.yslwcbv.mongodb.net/wishlist-db?retryWrites=true&w=majority}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
